<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="elmo_test_rig" >

  <xacro:include filename="$(find cob_description)/urdf/common.xacro" />
  <xacro:include filename="$(find cob_description)/urdf/materials.urdf.xacro" />

  <property name="base_height" value="0.04" />
  <property name="base_radius" value="0.01" />
  <property name="plate_height" value="0.01" />
  <property name="plate_radius" value="0.03" />
  
  <link name="base_link" >
    <visual>
      <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="${base_radius}" length="${base_height}" mass="0.100">
      <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>

  <joint name="plate_joint" type="revolute">
    <parent link="base_link" />
    <child link = "plate_link" />
    <origin xyz="0.0 0.0 ${base_height}" rpy="0.0 0.0 0.0" />
    <axis xyz="0 0 1" />
    <limit lower="${-M_PI}" upper="${M_PI}" effort="10.0" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="plate_link" >
    <visual>
      <origin xyz="0.0 0.0 ${plate_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${plate_height}" radius="${plate_radius}" />
      </geometry>
      <material name="IPA/Blue"/>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${plate_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${plate_height}" radius="${plate_radius}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="${plate_radius}" length="${plate_height}" mass="0.100">
      <origin xyz="0.0 0.0 ${plate_height/2}" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>


</robot>
